name: test-doctopus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.ssh.HOST }}
          username: ${{ env.ssh.USERNAME }}
          password: ${{ env.ssh.PASSWORD }}
          port: ${{ env.ssh.PORT }}
          script: whoami